package simpsonsdb.models;
// Generated 30-ene-2015 17:39:50 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Empleo generated by hbm2java
 */
public class Empleo  implements java.io.Serializable {


     private Integer idEmpleo;
     private String nombreEmpleo;
     private String descripcion;
     private Set personajes = new HashSet(0);

    public Empleo() {
    }

    public Empleo(String nombreEmpleo, String descripcion, Set personajes) {
       this.nombreEmpleo = nombreEmpleo;
       this.descripcion = descripcion;
       this.personajes = personajes;
    }
   
    public Integer getIdEmpleo() {
        return this.idEmpleo;
    }
    
    public void setIdEmpleo(Integer idEmpleo) {
        this.idEmpleo = idEmpleo;
    }
    public String getNombreEmpleo() {
        return this.nombreEmpleo;
    }
    
    public void setNombreEmpleo(String nombreEmpleo) {
        this.nombreEmpleo = nombreEmpleo;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public Set getPersonajes() {
        return this.personajes;
    }
    
    public void setPersonajes(Set personajes) {
        this.personajes = personajes;
    }




}


