package simpsonsdb.models;
// Generated 30-ene-2015 17:39:50 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Familia generated by hbm2java
 */
public class Familia  implements java.io.Serializable {


     private Integer idFamilia;
     private String nombre;
     private String descripcion;
     private Set personajes = new HashSet(0);

    public Familia() {
    }

    public Familia(String nombre, String descripcion, Set personajes) {
       this.nombre = nombre;
       this.descripcion = descripcion;
       this.personajes = personajes;
    }
    
    public Integer getIdFamilia() {
        return this.idFamilia;
    }
    
    public void setIdFamilia(Integer idFamilia) {
        this.idFamilia = idFamilia;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public Set getPersonajes() {
        return this.personajes;
    }
    
    public void setPersonajes(Set personajes) {
        this.personajes = personajes;
    }




}


