package simpsonsdb.models;
// Generated 30-ene-2015 17:39:50 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Lugar generated by hbm2java
 */
public class Lugar  implements java.io.Serializable {


     private Integer idLugar;
     private String nombreLugar;
     private String descripcion;
     private Set personajes = new HashSet(0);

    public Lugar() {
    }

    public Lugar(String nombreLugar, String descripcion, Set personajes) {
       this.nombreLugar = nombreLugar;
       this.descripcion = descripcion;
       this.personajes = personajes;
    }
   
    public Lugar(String nombreLugar, String descripcion) {
       this.nombreLugar = nombreLugar;
       this.descripcion = descripcion;
    }
    
    public Integer getIdLugar() {
        return this.idLugar;
    }
    
    public void setIdLugar(Integer idLugar) {
        this.idLugar = idLugar;
    }
    public String getNombreLugar() {
        return this.nombreLugar;
    }
    
    public void setNombreLugar(String nombreLugar) {
        this.nombreLugar = nombreLugar;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public Set getPersonajes() {
        return this.personajes;
    }
    
    public void setPersonajes(Set personajes) {
        this.personajes = personajes;
    }




}


