package simpsonsdb.models;
// Generated 30-ene-2015 17:39:50 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Personaje generated by hbm2java
 */
public class Personaje  implements java.io.Serializable {


     private Integer idPersonaje;
     private Familia familia;
     private String nombre;
     private String apellidos;
     private Integer edad;
     private String descripcion;
     private Set lugars = new HashSet(0);
     private Set empleos = new HashSet(0);

    public Personaje() {
    }

    public Personaje(Familia familia, String nombre, String apellidos, Integer edad, String descripcion, Set lugars, Set empleos) {
       this.familia = familia;
       this.nombre = nombre;
       this.apellidos = apellidos;
       this.edad = edad;
       this.descripcion = descripcion;
       this.lugars = lugars;
       this.empleos = empleos;
    }
    
    public Personaje(Familia familia, String nombre, String apellidos, Integer edad, String descripcion) {
       this.familia = familia;
       this.nombre = nombre;
       this.apellidos = apellidos;
       this.edad = edad;
       this.descripcion = descripcion;
    }
    
    public Integer getIdPersonaje() {
        return this.idPersonaje;
    }
    
    public void setIdPersonaje(Integer idPersonaje) {
        this.idPersonaje = idPersonaje;
    }
    public Familia getFamilia() {
        return this.familia;
    }
    
    public void setFamilia(Familia familia) {
        this.familia = familia;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getApellidos() {
        return this.apellidos;
    }
    
    public void setApellidos(String apellidos) {
        this.apellidos = apellidos;
    }
    public Integer getEdad() {
        return this.edad;
    }
    
    public void setEdad(Integer edad) {
        this.edad = edad;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public Set getLugars() {
        return this.lugars;
    }
    
    public void setLugars(Set lugars) {
        this.lugars = lugars;
    }
    public Set getEmpleos() {
        return this.empleos;
    }
    
    public void setEmpleos(Set empleos) {
        this.empleos = empleos;
    }




}


